export const countryJSON = [
{ name: 'Afghanistan', value: 'AF', id: 1 },
{ name: 'Åland Islands', value: 'AX', id: 2 },
{ name: 'Albania', value: 'AL', id: 3 },
{ name: 'Algeria', value: 'DZ', id: 4 },
{ name: 'American Samoa', value: 'AS', id: 5 },
{ name: 'AndorrA', value: 'AD', id: 6 },
{ name: 'Angola', value: 'AO', id: 7 },
{ name: 'Anguilla', value: 'AI', id: 8 },
{ name: 'Antarctica', value: 'AQ', id: 9 },
{ name: 'Antigua and Barbuda', value: 'AG', id: 10 },
{ name: 'Argentina', value: 'AR', id: 11 },
{ name: 'Armenia', value: 'AM', id: 12 },
{ name: 'Aruba', value: 'AW', id: 13 },
{ name: 'Australia', value: 'AU', id: 14 },
{ name: 'Austria', value: 'AT', id: 15 },
{ name: 'Azerbaijan', value: 'AZ', id: 16 },
{ name: 'Bahamas', value: 'BS', id: 17 },
{ name: 'Bahrain', value: 'BH', id: 18 },
{ name: 'Bangladesh', value: 'BD', id: 19 },
{ name: 'Barbados', value: 'BB', id: 20 },
{ name: 'Belarus', value: 'BY', id: 21 },
{ name: 'Belgium', value: 'BE', id: 22 },
{ name: 'Belize', value: 'BZ', id: 23 },
{ name: 'Benin', value: 'BJ', id: 24 },
{ name: 'Bermuda', value: 'BM', id: 25 },
{ name: 'Bhutan', value: 'BT', id: 26 },
{ name: 'Bolivia', value: 'BO', id: 27 },
{ name: 'Bosnia and Herzegovina', value: 'BA', id: 28 },
{ name: 'Botswana', value: 'BW', id: 29 },
{ name: 'Bouvet Island', value: 'BV', id: 30 },
{ name: 'Brazil', value: 'BR', id: 31 },
{ name: 'British Indian Ocean Territory', value: 'IO', id: 32 },
{ name: 'Brunei Darussalam', value: 'BN', id: 33 },
{ name: 'Bulgaria', value: 'BG', id: 34 },
{ name: 'Burkina Faso', value: 'BF', id: 35 },
{ name: 'Burundi', value: 'BI', id: 36 },
{ name: 'Cambodia', value: 'KH', id: 37 },
{ name: 'Cameroon', value: 'CM', id: 38 },
{ name: 'Canada', value: 'CA', id: 39 },
{ name: 'Cape Verde', value: 'CV', id: 40 },
{ name: 'Cayman Islands', value: 'KY', id: 41 },
{ name: 'Central African Republic', value: 'CF', id: 42 },
{ name: 'Chad', value: 'TD', id: 43 },
{ name: 'Chile', value: 'CL', id: 44 },
{ name: 'China', value: 'CN', id: 45 },
{ name: 'Christmas Island', value: 'CX', id: 46 },
{ name: 'Cocos (Keeling) Islands', value: 'CC', id: 47 },
{ name: 'Colombia', value: 'CO', id: 48 },
{ name: 'Comoros', value: 'KM', id: 49 },
{ name: 'Congo', value: 'CG', id: 50 },
{ name: 'Congo, The Democratic Republic of the', value: 'CD', id: 51 },
{ name: 'Cook Islands', value: 'CK', id: 52 },
{ name: 'Costa Rica', value: 'CR', id: 53 },
{ name: 'Cote D\'Ivoire', value: 'CI', id: 54 },
{ name: 'Croatia', value: 'HR', id: 55 },
{ name: 'Cuba', value: 'CU', id: 56 },
{ name: 'Cyprus', value: 'CY', id: 57 },
{ name: 'Czech Republic', value: 'CZ', id: 58 },
{ name: 'Denmark', value: 'DK', id: 59 },
{ name: 'Djibouti', value: 'DJ', id: 60 },
{ name: 'Dominica', value: 'DM', id: 61 },
{ name: 'Dominican Republic', value: 'DO', id: 62 },
{ name: 'Ecuador', value: 'EC', id: 63 },
{ name: 'Egypt', value: 'EG', id: 64 },
{ name: 'El Salvador', value: 'SV', id: 65 },
{ name: 'Equatorial Guinea', value: 'GQ', id: 66 },
{ name: 'Eritrea', value: 'ER', id: 67 },
{ name: 'Estonia', value: 'EE', id: 68 },
{ name: 'Ethiopia', value: 'ET', id: 69 },
{ name: 'Falkland Islands (Malvinas)', value: 'FK', id: 70 },
{ name: 'Faroe Islands', value: 'FO', id: 71 },
{ name: 'Fiji', value: 'FJ', id: 72 },
{ name: 'Finland', value: 'FI', id: 73 },
{ name: 'France', value: 'FR', id: 74 },
{ name: 'French Guiana', value: 'GF', id: 75 },
{ name: 'French Polynesia', value: 'PF', id: 76 },
{ name: 'French Southern Territories', value: 'TF', id: 77 },
{ name: 'Gabon', value: 'GA', id: 78 },
{ name: 'Gambia', value: 'GM', id: 79 },
{ name: 'Georgia', value: 'GE', id: 80 },
{ name: 'Germany', value: 'DE', id: 81 },
{ name: 'Ghana', value: 'GH', id: 82 },
{ name: 'Gibraltar', value: 'GI', id: 83 },
{ name: 'Greece', value: 'GR', id: 84 },
{ name: 'Greenland', value: 'GL', id: 85 },
{ name: 'Grenada', value: 'GD', id: 86 },
{ name: 'Guadeloupe', value: 'GP', id: 87 },
{ name: 'Guam', value: 'GU', id: 88 },
{ name: 'Guatemala', value: 'GT', id: 89 },
{ name: 'Guernsey', value: 'GG', id: 90 },
{ name: 'Guinea', value: 'GN', id: 91 },
{ name: 'Guinea-Bissau', value: 'GW', id: 92 },
{ name: 'Guyana', value: 'GY', id: 93 },
{ name: 'Haiti', value: 'HT', id: 94 },
{ name: 'Heard Island and Mcdonald Islands', value: 'HM', id: 95 },
{ name: 'Holy See (Vatican City State)', value: 'VA', id: 96 },
{ name: 'Honduras', value: 'HN', id: 97 },
{ name: 'Hong Kong', value: 'HK', id: 98 },
{ name: 'Hungary', value: 'HU', id: 99 },
{ name: 'Iceland', value: 'IS', id: 100 },
{ name: 'India', value: 'IN', id: 101 },
{ name: 'Indonesia', value: 'ID', id: 102 },
{ name: 'Iran, Islamic Republic Of', value: 'IR', id: 103 },
{ name: 'Iraq', value: 'IQ', id: 104 },
{ name: 'Ireland', value: 'IE', id: 105 },
{ name: 'Isle of Man', value: 'IM', id: 106 },
{ name: 'Israel', value: 'IL', id: 107 },
{ name: 'Italy', value: 'IT', id: 108 },
{ name: 'Jamaica', value: 'JM', id: 109 },
{ name: 'Japan', value: 'JP', id: 110 },
{ name: 'Jersey', value: 'JE', id: 111 },
{ name: 'Jordan', value: 'JO', id: 112 },
{ name: 'Kazakhstan', value: 'KZ', id: 113 },
{ name: 'Kenya', value: 'KE', id: 114 },
{ name: 'Kiribati', value: 'KI', id: 115 },
{ name: 'Korea, Democratic People\'S Republic of', value: 'KP', id: 116 },
{ name: 'Korea, Republic of', value: 'KR', id: 117 },
{ name: 'Kuwait', value: 'KW', id: 118 },
{ name: 'Kyrgyzstan', value: 'KG', id: 119 },
{ name: 'Lao People\'S Democratic Republic', value: 'LA', id: 120 },
{ name: 'Latvia', value: 'LV', id: 121 },
{ name: 'Lebanon', value: 'LB', id: 122 },
{ name: 'Lesotho', value: 'LS', id: 123 },
{ name: 'Liberia', value: 'LR', id: 124 },
{ name: 'Libyan Arab Jamahiriya', value: 'LY', id: 125 },
{ name: 'Liechtenstein', value: 'LI', id: 126 },
{ name: 'Lithuania', value: 'LT', id: 127 },
{ name: 'Luxembourg', value: 'LU', id: 128 },
{ name: 'Macao', value: 'MO', id: 129 },
{ name: 'Macedonia, The Former Yugoslav Republic of', value: 'MK', id: 130 },
{ name: 'Madagascar', value: 'MG', id: 131 },
{ name: 'Malawi', value: 'MW', id: 132 },
{ name: 'Malaysia', value: 'MY', id: 133 },
{ name: 'Maldives', value: 'MV', id: 134 },
{ name: 'Mali', value: 'ML', id: 135 },
{ name: 'Malta', value: 'MT', id: 136 },
{ name: 'Marshall Islands', value: 'MH', id: 137 },
{ name: 'Martinique', value: 'MQ', id: 138 },
{ name: 'Mauritania', value: 'MR', id: 139 },
{ name: 'Mauritius', value: 'MU', id: 140 },
{ name: 'Mayotte', value: 'YT', id: 141 },
{ name: 'Mexico', value: 'MX', id: 142 },
{ name: 'Micronesia, Federated States of', value: 'FM', id: 143 },
{ name: 'Moldova, Republic of', value: 'MD', id: 144 },
{ name: 'Monaco', value: 'MC', id: 145 },
{ name: 'Mongolia', value: 'MN', id: 146 },
{ name: 'Montserrat', value: 'MS', id: 147 },
{ name: 'Morocco', value: 'MA', id: 148 },
{ name: 'Mozambique', value: 'MZ', id: 149 },
{ name: 'Myanmar', value: 'MM', id: 150 },
{ name: 'Namibia', value: 'NA', id: 151 },
{ name: 'Nauru', value: 'NR', id: 152 },
{ name: 'Nepal', value: 'NP', id: 153 },
{ name: 'Netherlands', value: 'NL', id: 154 },
{ name: 'Netherlands Antilles', value: 'AN', id: 155 },
{ name: 'New Caledonia', value: 'NC', id: 156 },
{ name: 'New Zealand', value: 'NZ', id: 157 },
{ name: 'Nicaragua', value: 'NI', id: 158 },
{ name: 'Niger', value: 'NE', id: 159 },
{ name: 'Nigeria', value: 'NG', id: 160 },
{ name: 'Niue', value: 'NU', id: 161 },
{ name: 'Norfolk Island', value: 'NF', id: 162 },
{ name: 'Northern Mariana Islands', value: 'MP', id: 163 },
{ name: 'Norway', value: 'NO', id: 164 },
{ name: 'Oman', value: 'OM', id: 165 },
{ name: 'Pakistan', value: 'PK', id: 166 },
{ name: 'Palau', value: 'PW', id: 167 },
{ name: 'Palestinian Territory, Occupied', value: 'PS', id: 168 },
{ name: 'Panama', value: 'PA', id: 169 },
{ name: 'Papua New Guinea', value: 'PG', id: 170 },
{ name: 'Paraguay', value: 'PY', id: 171 },
{ name: 'Peru', value: 'PE', id: 172 },
{ name: 'Philippines', value: 'PH', id: 173 },
{ name: 'Pitcairn', value: 'PN', id: 174 },
{ name: 'Poland', value: 'PL', id: 175 },
{ name: 'Portugal', value: 'PT', id: 176 },
{ name: 'Puerto Rico', value: 'PR', id: 177 },
{ name: 'Qatar', value: 'QA', id: 178 },
{ name: 'Reunion', value: 'RE', id: 179 },
{ name: 'Romania', value: 'RO', id: 180 },
{ name: 'Russian Federation', value: 'RU', id: 181 },
{ name: 'RWANDA', value: 'RW', id: 182 },
{ name: 'Saint Helena', value: 'SH', id: 183 },
{ name: 'Saint Kitts and Nevis', value: 'KN', id: 184 },
{ name: 'Saint Lucia', value: 'LC', id: 185 },
{ name: 'Saint Pierre and Miquelon', value: 'PM', id: 186 },
{ name: 'Saint Vincent and the Grenadines', value: 'VC', id: 187 },
{ name: 'Samoa', value: 'WS', id: 188 },
{ name: 'San Marino', value: 'SM', id: 189 },
{ name: 'Sao Tome and Principe', value: 'ST', id: 190 },
{ name: 'Saudi Arabia', value: 'SA', id: 191 },
{ name: 'Senegal', value: 'SN', id: 192 },
{ name: 'Serbia and Montenegro', value: 'CS', id: 193 },
{ name: 'Seychelles', value: 'SC', id: 194 },
{ name: 'Sierra Leone', value: 'SL', id: 195 },
{ name: 'Singapore', value: 'SG', id: 196 },
{ name: 'Slovakia', value: 'SK', id: 197 },
{ name: 'Slovenia', value: 'SI', id: 198 },
{ name: 'Solomon Islands', value: 'SB', id: 199 },
{ name: 'Somalia', value: 'SO', id: 200 },
{ name: 'South Africa', value: 'ZA', id: 201 },
{ name: 'South Georgia and the South Sandwich Islands', value: 'GS', id: 202 },
{ name: 'Spain', value: 'ES', id: 203 },
{ name: 'Sri Lanka', value: 'LK', id: 204 },
{ name: 'Sudan', value: 'SD', id: 205 },
{ name: 'Suriname', value: 'SR', id: 206 },
{ name: 'Svalbard and Jan Mayen', value: 'SJ', id: 207 },
{ name: 'Swaziland', value: 'SZ', id: 208 },
{ name: 'Sweden', value: 'SE', id: 209 },
{ name: 'Switzerland', value: 'CH', id: 210 },
{ name: 'Syrian Arab Republic', value: 'SY', id: 211 },
{ name: 'Taiwan, Province of China', value: 'TW', id: 212 },
{ name: 'Tajikistan', value: 'TJ', id: 213 },
{ name: 'Tanzania, United Republic of', value: 'TZ', id: 214 },
{ name: 'Thailand', value: 'TH', id: 215 },
{ name: 'Timor-Leste', value: 'TL', id: 216 },
{ name: 'Togo', value: 'TG', id: 217 },
{ name: 'Tokelau', value: 'TK', id: 218 },
{ name: 'Tonga', value: 'TO', id: 219 },
{ name: 'Trinidad and Tobago', value: 'TT', id: 220 },
{ name: 'Tunisia', value: 'TN', id: 221 },
{ name: 'Turkey', value: 'TR', id: 222 },
{ name: 'Turkmenistan', value: 'TM', id: 223 },
{ name: 'Turks and Caicos Islands', value: 'TC', id: 224 },
{ name: 'Tuvalu', value: 'TV', id: 225 },
{ name: 'Uganda', value: 'UG', id: 226 },
{ name: 'Ukraine', value: 'UA', id: 227 },
{ name: 'United Arab Emirates', value: 'AE', id: 228 },
{ name: 'United Kingdom', value: 'GB', id: 229 },
{ name: 'United States', value: 'US', id: 230 },
{ name: 'United States Minor Outlying Islands', value: 'UM', id: 231 },
{ name: 'Uruguay', value: 'UY', id: 232 },
{ name: 'Uzbekistan', value: 'UZ', id: 233 },
{ name: 'Vanuatu', value: 'VU', id: 234 },
{ name: 'Venezuela', value: 'VE', id: 235 },
{ name: 'Viet Nam', value: 'VN', id: 236 },
{ name: 'Virgin Islands, British', value: 'VG', id: 237 },
{ name: 'Virgin Islands, U.S.', value: 'VI', id: 238 },
{ name: 'Wallis and Futuna', value: 'WF', id: 239 },
{ name: 'Western Sahara', value: 'EH', id: 240 },
{ name: 'Yemen', value: 'YE', id: 241 },
{ name: 'Zambia', value: 'ZM', id: 242 },
{ name: 'Zimbabwe', value: 'ZW', id: 243 }
];
